Update patch set 3
Change has been successfully cherry-picked as 8530f5032a0ee22c03657b5ef7c44e0a3072294c

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: cue/compile.py
Insertions: 2, Deletions: 2.

@@ -30,7 +30,7 @@
     buf = libcue.ffi.new("char[]", s.encode("utf-8"))
 
     build_opts = encode_build_opts(*opts)
-    err = libcue.compile_string(ctx.res(), buf, build_opts, val_ptr)
+    err = libcue.compile_string(ctx._res(), buf, build_opts, val_ptr)
     if err != 0:
         raise Error(err)
     return Value(ctx, val_ptr[0])
@@ -40,7 +40,7 @@
     buf_ptr = libcue.ffi.from_buffer(buf)
 
     build_opts = encode_build_opts(*opts)
-    err = libcue.compile_bytes(ctx.res(), buf_ptr, len(buf), build_opts, val_ptr)
+    err = libcue.compile_bytes(ctx._res(), buf_ptr, len(buf), build_opts, val_ptr)
     if err != 0:
         raise Error(err)
     return Value(ctx, val_ptr[0])
```
```
The name of the file: cue/context.py
Insertions: 12, Deletions: 12.

@@ -21,7 +21,7 @@
 from cue.value import Value
 from cue.build import BuildOption
 from cue.compile import compile, compile_bytes
-from cue.res import Resource
+from cue.res import _Resource
 import libcue
 
 @final
@@ -36,12 +36,12 @@
     https://pkg.go.dev/cuelang.org/go/cue#Context
     """
 
-    _ctx: Resource
+    _ctx: _Resource
 
     def __init__(self):
-        self._ctx = Resource(libcue.newctx())
+        self._ctx = _Resource(libcue.newctx())
 
-    def res(self) -> int:
+    def _res(self) -> int:
         return self._ctx.res()
 
     @singledispatchmethod
@@ -77,13 +77,13 @@
         """
         Return an instance of CUE `_`.
         """
-        return Value(self, libcue.top(self.res()))
+        return Value(self, libcue.top(self._res()))
 
     def bottom(self) -> Value:
         """
         Return an instance of CUE `_|_`.
         """
-        return Value(self, libcue.bottom(self.res()))
+        return Value(self, libcue.bottom(self._res()))
 
     @singledispatchmethod
     def to_value(self, arg) -> Value:
@@ -100,25 +100,25 @@
 
     @to_value.register
     def _(self, arg: int):
-        return Value(self, libcue.from_int64(self.res(), arg))
+        return Value(self, libcue.from_int64(self._res(), arg))
 
     @to_value.register
     def _(self, arg: bool):
-        return Value(self, libcue.from_bool(self.res(), arg))
+        return Value(self, libcue.from_bool(self._res(), arg))
 
     @to_value.register
     def _(self, arg: float):
-        return Value(self, libcue.from_double(self.res(), arg))
+        return Value(self, libcue.from_double(self._res(), arg))
 
     @to_value.register
     def _(self, arg: str):
         c_str = libcue.ffi.new("char[]", arg.encode("utf-8"))
-        return Value(self, libcue.from_string(self.res(), c_str))
+        return Value(self, libcue.from_string(self._res(), c_str))
 
     @to_value.register
     def _(self, arg: bytes):
         c_buf = libcue.ffi.from_buffer(arg)
-        return Value(self, libcue.from_bytes(self.res(), c_buf, len(arg)))
+        return Value(self, libcue.from_bytes(self._res(), c_buf, len(arg)))
 
     def to_value_from_unsigned(self, arg: int) -> Value:
         """
@@ -132,4 +132,4 @@
         Return:
             Value: the CUE value denoting arg.
         """
-        return Value(self, libcue.from_uint64(self.res(), arg))
+        return Value(self, libcue.from_uint64(self._res(), arg))
```
```
The name of the file: cue/error.py
Insertions: 5, Deletions: 5.

@@ -17,7 +17,7 @@
 """
 
 from typing import final
-from cue.res import Resource
+from cue.res import _Resource
 import libcue
 
 @final
@@ -26,16 +26,16 @@
     CUE evaluation error.
     """
 
-    _err: Resource
+    _err: _Resource
 
-    def res(self):
+    def _res(self):
         return self._err.res()
 
     def __init__(self, err: int):
-        self._err = Resource(err)
+        self._err = _Resource(err)
 
     def __str__(self):
-        c_str = libcue.error_string(self.res())
+        c_str = libcue.error_string(self._res())
         s = libcue.ffi.string(c_str).decode("utf-8")
         libcue.libc_free(c_str)
         return s
```
```
The name of the file: cue/res.py
Insertions: 4, Deletions: 1.

@@ -20,7 +20,7 @@
 import libcue
 
 @final
-class Resource:
+class _Resource:
     """
     A CUE resource.
 
@@ -29,6 +29,9 @@
 
     _val: int
 
+    """
+    Returns the underlying Go resoure handle.
+    """
     def res(self) -> int:
         if self._val != 0:
             return self._val
```
```
The name of the file: cue/value.py
Insertions: 20, Deletions: 20.

@@ -20,7 +20,7 @@
 from cue.error import Error
 from cue.eval import EvalOption, encode_eval_opts
 from cue.kind import Kind, to_kind
-from cue.res import Resource
+from cue.res import _Resource
 from cue.result import Result, Ok, Err
 import libcue
 
@@ -40,13 +40,13 @@
     """
 
     _ctx: 'Context'
-    _val: Resource
+    _val: _Resource
 
     def __init__(self, ctx: 'Context', v: int):
         self._ctx = ctx
-        self._val = Resource(v)
+        self._val = _Resource(v)
 
-    def res(self) -> int:
+    def _res(self) -> int:
         return self._val.res()
 
     def __eq__(self, other: Any) -> bool:
@@ -66,7 +66,7 @@
             bool: True if the two values are complete and equal CUE values, False otherwise.
         """
         if isinstance(other, Value):
-            return libcue.is_equal(self.res(), other.res())
+            return libcue.is_equal(self._res(), other._res())
         return False
 
     def context(self) -> 'Context':
@@ -80,7 +80,7 @@
         Corresponding Go functionality is documented at:
         https://pkg.go.dev/cuelang.org/go/cue#Value.Unify
         """
-        v = libcue.unify(self.res(), other.res())
+        v = libcue.unify(self._res(), other._res())
         return Value(self._ctx, v)
 
     def lookup(self, path: str) -> 'Value':
@@ -235,7 +235,7 @@
         Corresponding Go functionality is documented at:
         https://pkg.go.dev/cuelang.org/go/cue#Value.Kind
         """
-        return to_kind[libcue.concrete_kind(self.res())]
+        return to_kind[libcue.concrete_kind(self._res())]
 
     def incomplete_kind(self) -> Kind:
         """
@@ -244,7 +244,7 @@
         Corresponding Go functionality is documented at:
         https://pkg.go.dev/cuelang.org/go/cue#Value.IncompleteKind
         """
-        return to_kind[libcue.incomplete_kind(self.res())]
+        return to_kind[libcue.incomplete_kind(self._res())]
 
     def error(self) -> Result['Value', str]:
         """
@@ -253,7 +253,7 @@
         Returns:
             Result['Value', str]: the value itself, if there is no error, or the CUE error as a string if there is one.
         """
-        err = libcue.value_error(self.res())
+        err = libcue.value_error(self._res())
         if err != 0:
             c_str = libcue.error_string(err)
 
@@ -282,7 +282,7 @@
         """
 
         eval_opts = encode_eval_opts(*opts)
-        err = libcue.instance_of(self.res(), schema.res(), eval_opts)
+        err = libcue.instance_of(self._res(), schema._res(), eval_opts)
         if err != 0:
             raise Error(err)
 
@@ -300,41 +300,41 @@
             Error: if the value contains errors.
         """
         eval_opts = encode_eval_opts(*opts)
-        err = libcue.validate(self.res(), eval_opts)
+        err = libcue.validate(self._res(), eval_opts)
         if err != 0:
             raise Error(err)
 
 def _to_int(val: Value) -> int:
     ptr = libcue.ffi.new("int64_t*")
-    err = libcue.dec_int64(val.res(), ptr)
+    err = libcue.dec_int64(val._res(), ptr)
     if err != 0:
         raise Error(err)
     return ptr[0]
 
 def _to_unsigned(val: Value) -> int:
     ptr = libcue.ffi.new("uint64_t*")
-    err = libcue.dec_uint64(val.res(), ptr)
+    err = libcue.dec_uint64(val._res(), ptr)
     if err != 0:
         raise Error(err)
     return ptr[0]
 
 def _to_bool(val: Value) -> bool:
     ptr = libcue.ffi.new("bool*")
-    err = libcue.dec_bool(val.res(), ptr)
+    err = libcue.dec_bool(val._res(), ptr)
     if err != 0:
         raise Error(err)
     return ptr[0]
 
 def _to_float(val: Value) -> float:
     ptr = libcue.ffi.new("double*")
-    err = libcue.dec_double(val.res(), ptr)
+    err = libcue.dec_double(val._res(), ptr)
     if err != 0:
         raise Error(err)
     return ptr[0]
 
 def _to_str(val: Value) -> str:
     ptr = libcue.ffi.new("char**")
-    err = libcue.dec_string(val.res(), ptr)
+    err = libcue.dec_string(val._res(), ptr)
     if err != 0:
         raise Error(err)
 
@@ -350,7 +350,7 @@
     buf_ptr = libcue.ffi.new("uint8_t**")
     len_ptr = libcue.ffi.new("size_t*")
 
-    err = libcue.dec_bytes(val.res(), buf_ptr, len_ptr)
+    err = libcue.dec_bytes(val._res(), buf_ptr, len_ptr)
     if err != 0:
         raise Error(err)
 
@@ -368,7 +368,7 @@
     buf_ptr = libcue.ffi.new("uint8_t**")
     len_ptr = libcue.ffi.new("size_t*")
 
-    err = libcue.dec_json(val.res(), buf_ptr, len_ptr)
+    err = libcue.dec_json(val._res(), buf_ptr, len_ptr)
     if err != 0:
         raise Error(err)
 
@@ -384,14 +384,14 @@
     val_ptr = libcue.ffi.new("cue_value*")
     path_ptr = libcue.ffi.new("char[]", path.encode("utf-8"))
 
-    err = libcue.lookup_string(val.res(), path_ptr, val_ptr)
+    err = libcue.lookup_string(val._res(), path_ptr, val_ptr)
     if err != 0:
         raise Error(err)
     return Value(val._ctx, val_ptr[0])
 
 def _default(val: Value) -> Optional[Value]:
     ok_ptr = libcue.ffi.new("bool*")
-    res = libcue.default(val.res(), ok_ptr)
+    res = libcue.default(val._res(), ok_ptr)
     if ok_ptr[0] == 1:
         return Value(val._ctx, res)
     return None
```
```
The name of the file: libcue/api.py
Insertions: 1, Deletions: 1.

@@ -137,7 +137,7 @@
     lib = ffi.dlopen("cue", ffi.RTLD_NODELETE)
 else:
     # On Windows we don't have RTLD_NODELETE. Create an artificial
-    # global references to lib, so we prevent unloading the shared
+    # global reference to lib, so we prevent unloading the shared
     # library.
     lib = ffi.dlopen("cue")
     sys.modules[__name__]._lib_reference = lib
```


Patch-set: 3
Subject: cue, libcue: fix spurious segmentation fault on program exit
Status: merged
Commit: 8530f5032a0ee22c03657b5ef7c44e0a3072294c
Tag: autogenerated:gerrit:merged
Groups: e530ff0401c28e4f92be46a6c59cdd31a314519f
Label: Code-Review=+2, d8e940dc5d1d28c9d73022934a17c20515a28437 Gerrit User 1007275 <1007275@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 1bd67531d9b271aa8c85d604066d04d39c33fd4b Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, c4773cc117d87bb8abff8c527f66b7962cfc7148
Submission-id: 1196751
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1007275 <1007275@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}